ERROR_FOR_BASIC_SAVINGS = 'BALANCE_EXCEDDING_IN_BASIC_SAVINGS'
ERROR_FOR_INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'
ERROR_FOR_SAME_ACCOUNT_ID = 'SAME_ACCOUNT_ID'

ERRORS_CODES = {
    ERROR_FOR_INSUFFICIENT_BALANCE: {'ERROR_CODE': 201,
                                     'ERROR_MESSAGE': "INSUFFICIENT BALANCE IN SOURCE ACCOUNT"},

    ERROR_FOR_BASIC_SAVINGS: {'ERROR_CODE': 202,
                              'ERROR_MESSAGE': "BALANCE EXCEEDING ABOVE 500000 RS IN DESTINATION ACCOUNT"},

    ERROR_FOR_SAME_ACCOUNT_ID : {'ERROR_CODE' : 203,
                                 'ERROR_MESSAGE' : "CANNOT PROCEED SOURCE AND DESTINATION ACCOUNT ARE SAME"}

    }

