ERROR_FOR_BASIC_SAVINGS = 'BALANCE_EXCEDDING_IN_BASIC_SAVINGS'
ERROR_FOR_INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'

ERRORS_CODES = {
    ERROR_FOR_INSUFFICIENT_BALANCE: {'ERROR_CODE': 201,
                                     'ERROR_MESSAGE': "INSUFFIECIENT BALANCE IN SOURCE ACCOUNT"},

    ERROR_FOR_BASIC_SAVINGS: {'ERROR_CODE': 202,
                              'ERROR_MESSAGE': "BALANCE EXCEEDING ABOVE 500000 RS IN DESTINATION ACCOUNT"}
}
